eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
spring:
   boot:
    admin:
      client:
        url:
        - http://admin:admin@localhost:8761/admin
   zipkin:
     base-url: http://localhost:9411
